// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhOU1DSqwQpmkymGJKE1P3o74RANMcqW4',
    appId: '1:984067873347:web:4261dbdfb3be7ae747d2f6',
    messagingSenderId: '984067873347',
    projectId: 'todoist-e401f',
    authDomain: 'todoist-e401f.firebaseapp.com',
    storageBucket: 'todoist-e401f.appspot.com',
    measurementId: 'G-P318ST0HSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1cmgpViaRexMYW7HINkbk4RQhP7rWJAg',
    appId: '1:984067873347:android:8b8d125ceae14e7947d2f6',
    messagingSenderId: '984067873347',
    projectId: 'todoist-e401f',
    storageBucket: 'todoist-e401f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC96V-xGpV8C0TZI0GBTM7FxUOFkoz_Jmk',
    appId: '1:984067873347:ios:7e48eac826297dc147d2f6',
    messagingSenderId: '984067873347',
    projectId: 'todoist-e401f',
    storageBucket: 'todoist-e401f.appspot.com',
    iosBundleId: 'com.example.todoist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC96V-xGpV8C0TZI0GBTM7FxUOFkoz_Jmk',
    appId: '1:984067873347:ios:d28b6265bac90ded47d2f6',
    messagingSenderId: '984067873347',
    projectId: 'todoist-e401f',
    storageBucket: 'todoist-e401f.appspot.com',
    iosBundleId: 'com.example.todoist.RunnerTests',
  );
}
